server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://${SERVICE_IP}:5432/postgres
    username: postgres
    password: ${POSTGRES_PWD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 550000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  application:
    name: rag-openai-dashscope-pgvector


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  ai:
    openai:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus-latest
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      pgvector:
        table-name: mxy_rag_vector
        initialize-schema: true
        dimensions: 1024
        index-type: hnsw